### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by sgharms** [IBM-Swift/Kitura-MustacheTemplateEngine#10]
I'm definitely jumping in wayyyy over my head here, but what would it take to get a Mustache template engine support?

I don't know if I could write the parser myself, but I'm _pretty_ sure that I could adapt a JS implementation to work here. Is that desirable here?

**Comment by vadimeisenbergibm** [comment]
@sgharms please see https://github.com/IBM-Swift/Kitura/issues/650#issuecomment-245366299 . Once the five issues specified in the comment are fixed in apple/swift, my guess is that most of the failing tests will pass. Then we will check further into the remaining problems, if any.

**Comment by ludagoo** [comment]
Can't this issue be closed now(93b7b26)? There is still a note on [this](http://www.kitura.io/en/resources/tutorials/templating.html) page saying linux is not supported.

**Comment by vadimeisenbergibm** [comment]
Hi @ludagoo, thank you for catching this - I will fix it on Tuesday.

**Comment by vadimeisenbergibm** [comment]
@ludagoo I have submitted a PR - https://github.com/IBM-Swift/kitura.io/pull/48.

**Comment by vadimeisenbergibm** [comment]
Fixed by https://github.com/IBM-Swift/Kitura/issues/1042. Now Mustache works on Linux starting from Linux 3.1. (It continues to work on macOS, as before).
